// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/marketdata.proto

// Protobuf Java Version: 3.25.5
package com.google.cloud.orderbook.model;

public final class MarketData {

  private MarketData() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_OrderBookEvent_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderBookEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_MarketDepth_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MarketDepth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_MarketDepth_PriceQuantity_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MarketDepth_PriceQuantity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\n\037src/main/proto/marketdata.proto\"\332\003\n\016Or" +
            "derBookEvent\022\023\n\013timestampMS\030\001 \001(\003\022\021\n\tses" +
            "sionId\030\021 \001(\t\022\022\n\ncontractId\030\002 \001(\003\022\r\n\005seqI" +
            "d\030\004 \001(\003\022\025\n\rcontractSeqId\030\005 \001(\003\022\023\n\013lastMe" +
            "ssage\030\006 \001(\010\022\033\n\023lastContractMessage\030\007 \001(\010" +
            "\022\"\n\004type\030\010 \001(\0162\024.OrderBookEvent.Type\022\017\n\007" +
            "orderId\030\t \001(\003\022\"\n\004side\030\n \001(\0162\024.OrderBookE" +
            "vent.Side\022\r\n\005price\030\013 \001(\003\022\020\n\010quantity\030\014 \001" +
            "(\003\022\031\n\021quantityRemaining\030\r \001(\003\022\026\n\016quantit" +
            "yFilled\030\016 \001(\003\022\023\n\013matchNumber\030\017 \001(\003\"A\n\004Ty" +
            "pe\022\025\n\021UNSPECIFIED_ORDER\020\000\022\007\n\003NEW\020\001\022\014\n\010EX" +
            "ECUTED\020\002\022\013\n\007DELETED\020\003\"/\n\004Side\022\024\n\020UNSPECI" +
            "FIED_SIDE\020\000\022\007\n\003BUY\020\001\022\010\n\004SELL\020\002\"\223\002\n\013Marke"
            +
            "tDepth\022\023\n\013timestampMS\030\001 \001(\003\022\022\n\ncontractI" +
            "d\030\002 \001(\003\022\r\n\005seqId\030\004 \001(\003\022\025\n\rcontractSeqId\030" +
            "\005 \001(\003\022(\n\004bids\030\006 \003(\0132\032.MarketDepth.PriceQ" +
            "uantity\022*\n\006offers\030\007 \003(\0132\032.MarketDepth.Pr" +
            "iceQuantity\022-\n\tlastTrade\030\010 \001(\0132\032.MarketD" +
            "epth.PriceQuantity\0320\n\rPriceQuantity\022\r\n\005p" +
            "rice\030\001 \001(\003\022\020\n\010quantity\030\002 \001(\003B0\n com.goog" +
            "le.cloud.orderbook.modelB\nMarketDataP\001b\006" +
            "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
            });
    internal_static_OrderBookEvent_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_OrderBookEvent_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderBookEvent_descriptor,
        new java.lang.String[]{"TimestampMS", "SessionId", "ContractId", "SeqId", "ContractSeqId",
            "LastMessage", "LastContractMessage", "Type", "OrderId", "Side", "Price", "Quantity",
            "QuantityRemaining", "QuantityFilled", "MatchNumber",});
    internal_static_MarketDepth_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_MarketDepth_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MarketDepth_descriptor,
        new java.lang.String[]{"TimestampMS", "ContractId", "SeqId", "ContractSeqId", "Bids",
            "Offers", "LastTrade",});
    internal_static_MarketDepth_PriceQuantity_descriptor =
        internal_static_MarketDepth_descriptor.getNestedTypes().get(0);
    internal_static_MarketDepth_PriceQuantity_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MarketDepth_PriceQuantity_descriptor,
        new java.lang.String[]{"Price", "Quantity",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
