/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata.proto

package com.google.cloud.orderbook.model;

/**
 * Protobuf type {@code MarketDepth}
 */
public final class MarketDepth extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MarketDepth)
    MarketDepthOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MarketDepth.newBuilder() to construct.
  private MarketDepth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MarketDepth() {
    bids_ = java.util.Collections.emptyList();
    offers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MarketDepth();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.orderbook.model.MarketDepth.class, com.google.cloud.orderbook.model.MarketDepth.Builder.class);
  }

  public interface PriceQuantityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MarketDepth.PriceQuantity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 price = 1;</code>
     * @return The price.
     */
    long getPrice();

    /**
     * <code>int64 quantity = 2;</code>
     * @return The quantity.
     */
    long getQuantity();
  }
  /**
   * <pre>
   * Current market depth (ordered by most significant to
   * least significant bid &amp; offer)
   * </pre>
   *
   * Protobuf type {@code MarketDepth.PriceQuantity}
   */
  public static final class PriceQuantity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MarketDepth.PriceQuantity)
      PriceQuantityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PriceQuantity.newBuilder() to construct.
    private PriceQuantity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PriceQuantity() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PriceQuantity();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_PriceQuantity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_PriceQuantity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.class, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder.class);
    }

    public static final int PRICE_FIELD_NUMBER = 1;
    private long price_ = 0L;
    /**
     * <code>int64 price = 1;</code>
     * @return The price.
     */
    @java.lang.Override
    public long getPrice() {
      return price_;
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private long quantity_ = 0L;
    /**
     * <code>int64 quantity = 2;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public long getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (price_ != 0L) {
        output.writeInt64(1, price_);
      }
      if (quantity_ != 0L) {
        output.writeInt64(2, quantity_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (price_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, price_);
      }
      if (quantity_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, quantity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.cloud.orderbook.model.MarketDepth.PriceQuantity)) {
        return super.equals(obj);
      }
      com.google.cloud.orderbook.model.MarketDepth.PriceQuantity other = (com.google.cloud.orderbook.model.MarketDepth.PriceQuantity) obj;

      if (getPrice()
          != other.getPrice()) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrice());
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQuantity());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.cloud.orderbook.model.MarketDepth.PriceQuantity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Current market depth (ordered by most significant to
     * least significant bid &amp; offer)
     * </pre>
     *
     * Protobuf type {@code MarketDepth.PriceQuantity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MarketDepth.PriceQuantity)
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_PriceQuantity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_PriceQuantity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.class, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder.class);
      }

      // Construct using com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        price_ = 0L;
        quantity_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_PriceQuantity_descriptor;
      }

      @java.lang.Override
      public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getDefaultInstanceForType() {
        return com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity build() {
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity buildPartial() {
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity result = new com.google.cloud.orderbook.model.MarketDepth.PriceQuantity(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.cloud.orderbook.model.MarketDepth.PriceQuantity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.quantity_ = quantity_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.cloud.orderbook.model.MarketDepth.PriceQuantity) {
          return mergeFrom((com.google.cloud.orderbook.model.MarketDepth.PriceQuantity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.cloud.orderbook.model.MarketDepth.PriceQuantity other) {
        if (other == com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance()) return this;
        if (other.getPrice() != 0L) {
          setPrice(other.getPrice());
        }
        if (other.getQuantity() != 0L) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                price_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                quantity_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long price_ ;
      /**
       * <code>int64 price = 1;</code>
       * @return The price.
       */
      @java.lang.Override
      public long getPrice() {
        return price_;
      }
      /**
       * <code>int64 price = 1;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(long value) {

        price_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 price = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0L;
        onChanged();
        return this;
      }

      private long quantity_ ;
      /**
       * <code>int64 quantity = 2;</code>
       * @return The quantity.
       */
      @java.lang.Override
      public long getQuantity() {
        return quantity_;
      }
      /**
       * <code>int64 quantity = 2;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(long value) {

        quantity_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 quantity = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MarketDepth.PriceQuantity)
    }

    // @@protoc_insertion_point(class_scope:MarketDepth.PriceQuantity)
    private static final com.google.cloud.orderbook.model.MarketDepth.PriceQuantity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.cloud.orderbook.model.MarketDepth.PriceQuantity();
    }

    public static com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PriceQuantity>
        PARSER = new com.google.protobuf.AbstractParser<PriceQuantity>() {
      @java.lang.Override
      public PriceQuantity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PriceQuantity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PriceQuantity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int TIMESTAMPMS_FIELD_NUMBER = 1;
  private long timestampMS_ = 0L;
  /**
   * <pre>
   * Millisecond timestmp
   * </pre>
   *
   * <code>int64 timestampMS = 1;</code>
   * @return The timestampMS.
   */
  @java.lang.Override
  public long getTimestampMS() {
    return timestampMS_;
  }

  public static final int CONTRACTID_FIELD_NUMBER = 2;
  private long contractId_ = 0L;
  /**
   * <pre>
   * Contract ID (unique ordering)
   * </pre>
   *
   * <code>int64 contractId = 2;</code>
   * @return The contractId.
   */
  @java.lang.Override
  public long getContractId() {
    return contractId_;
  }

  public static final int MESSAGEID_FIELD_NUMBER = 3;
  private long messageId_ = 0L;
  /**
   * <pre>
   * Message ID (corresponds to OrderBookEvent messageId)
   * </pre>
   *
   * <code>int64 messageId = 3;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public long getMessageId() {
    return messageId_;
  }

  public static final int SEQID_FIELD_NUMBER = 4;
  private long seqId_ = 0L;
  /**
   * <pre>
   * Sequence IDs (global and per contract) will skip
   * any updates that do not generate a market depth.
   * </pre>
   *
   * <code>int64 seqId = 4;</code>
   * @return The seqId.
   */
  @java.lang.Override
  public long getSeqId() {
    return seqId_;
  }

  public static final int CONTRACTSEQID_FIELD_NUMBER = 5;
  private long contractSeqId_ = 0L;
  /**
   * <code>int64 contractSeqId = 5;</code>
   * @return The contractSeqId.
   */
  @java.lang.Override
  public long getContractSeqId() {
    return contractSeqId_;
  }

  public static final int BIDS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> bids_;
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> getBidsList() {
    return bids_;
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
      getBidsOrBuilderList() {
    return bids_;
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  @java.lang.Override
  public int getBidsCount() {
    return bids_.size();
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  @java.lang.Override
  public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getBids(int index) {
    return bids_.get(index);
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  @java.lang.Override
  public com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getBidsOrBuilder(
      int index) {
    return bids_.get(index);
  }

  public static final int OFFERS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> offers_;
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> getOffersList() {
    return offers_;
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
      getOffersOrBuilderList() {
    return offers_;
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  @java.lang.Override
  public int getOffersCount() {
    return offers_.size();
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  @java.lang.Override
  public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getOffers(int index) {
    return offers_.get(index);
  }
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  @java.lang.Override
  public com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getOffersOrBuilder(
      int index) {
    return offers_.get(index);
  }

  public static final int LASTTRADE_FIELD_NUMBER = 8;
  private com.google.cloud.orderbook.model.MarketDepth.PriceQuantity lastTrade_;
  /**
   * <pre>
   * If a trade was executed for this event,
   * capture this here.
   * </pre>
   *
   * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
   * @return Whether the lastTrade field is set.
   */
  @java.lang.Override
  public boolean hasLastTrade() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * If a trade was executed for this event,
   * capture this here.
   * </pre>
   *
   * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
   * @return The lastTrade.
   */
  @java.lang.Override
  public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getLastTrade() {
    return lastTrade_ == null ? com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance() : lastTrade_;
  }
  /**
   * <pre>
   * If a trade was executed for this event,
   * capture this here.
   * </pre>
   *
   * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
   */
  @java.lang.Override
  public com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getLastTradeOrBuilder() {
    return lastTrade_ == null ? com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance() : lastTrade_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestampMS_ != 0L) {
      output.writeInt64(1, timestampMS_);
    }
    if (contractId_ != 0L) {
      output.writeInt64(2, contractId_);
    }
    if (messageId_ != 0L) {
      output.writeInt64(3, messageId_);
    }
    if (seqId_ != 0L) {
      output.writeInt64(4, seqId_);
    }
    if (contractSeqId_ != 0L) {
      output.writeInt64(5, contractSeqId_);
    }
    for (int i = 0; i < bids_.size(); i++) {
      output.writeMessage(6, bids_.get(i));
    }
    for (int i = 0; i < offers_.size(); i++) {
      output.writeMessage(7, offers_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(8, getLastTrade());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestampMS_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestampMS_);
    }
    if (contractId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, contractId_);
    }
    if (messageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, messageId_);
    }
    if (seqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, seqId_);
    }
    if (contractSeqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, contractSeqId_);
    }
    for (int i = 0; i < bids_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, bids_.get(i));
    }
    for (int i = 0; i < offers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, offers_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getLastTrade());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.orderbook.model.MarketDepth)) {
      return super.equals(obj);
    }
    com.google.cloud.orderbook.model.MarketDepth other = (com.google.cloud.orderbook.model.MarketDepth) obj;

    if (getTimestampMS()
        != other.getTimestampMS()) return false;
    if (getContractId()
        != other.getContractId()) return false;
    if (getMessageId()
        != other.getMessageId()) return false;
    if (getSeqId()
        != other.getSeqId()) return false;
    if (getContractSeqId()
        != other.getContractSeqId()) return false;
    if (!getBidsList()
        .equals(other.getBidsList())) return false;
    if (!getOffersList()
        .equals(other.getOffersList())) return false;
    if (hasLastTrade() != other.hasLastTrade()) return false;
    if (hasLastTrade()) {
      if (!getLastTrade()
          .equals(other.getLastTrade())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMPMS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMS());
    hash = (37 * hash) + CONTRACTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getContractId());
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageId());
    hash = (37 * hash) + SEQID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeqId());
    hash = (37 * hash) + CONTRACTSEQID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getContractSeqId());
    if (getBidsCount() > 0) {
      hash = (37 * hash) + BIDS_FIELD_NUMBER;
      hash = (53 * hash) + getBidsList().hashCode();
    }
    if (getOffersCount() > 0) {
      hash = (37 * hash) + OFFERS_FIELD_NUMBER;
      hash = (53 * hash) + getOffersList().hashCode();
    }
    if (hasLastTrade()) {
      hash = (37 * hash) + LASTTRADE_FIELD_NUMBER;
      hash = (53 * hash) + getLastTrade().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.orderbook.model.MarketDepth parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.orderbook.model.MarketDepth parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.orderbook.model.MarketDepth parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.orderbook.model.MarketDepth prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MarketDepth}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MarketDepth)
      com.google.cloud.orderbook.model.MarketDepthOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.orderbook.model.MarketDepth.class, com.google.cloud.orderbook.model.MarketDepth.Builder.class);
    }

    // Construct using com.google.cloud.orderbook.model.MarketDepth.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBidsFieldBuilder();
        getOffersFieldBuilder();
        getLastTradeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestampMS_ = 0L;
      contractId_ = 0L;
      messageId_ = 0L;
      seqId_ = 0L;
      contractSeqId_ = 0L;
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
      } else {
        bids_ = null;
        bidsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (offersBuilder_ == null) {
        offers_ = java.util.Collections.emptyList();
      } else {
        offers_ = null;
        offersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      lastTrade_ = null;
      if (lastTradeBuilder_ != null) {
        lastTradeBuilder_.dispose();
        lastTradeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_MarketDepth_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.orderbook.model.MarketDepth getDefaultInstanceForType() {
      return com.google.cloud.orderbook.model.MarketDepth.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.orderbook.model.MarketDepth build() {
      com.google.cloud.orderbook.model.MarketDepth result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.orderbook.model.MarketDepth buildPartial() {
      com.google.cloud.orderbook.model.MarketDepth result = new com.google.cloud.orderbook.model.MarketDepth(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.cloud.orderbook.model.MarketDepth result) {
      if (bidsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          bids_ = java.util.Collections.unmodifiableList(bids_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.bids_ = bids_;
      } else {
        result.bids_ = bidsBuilder_.build();
      }
      if (offersBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          offers_ = java.util.Collections.unmodifiableList(offers_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.offers_ = offers_;
      } else {
        result.offers_ = offersBuilder_.build();
      }
    }

    private void buildPartial0(com.google.cloud.orderbook.model.MarketDepth result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestampMS_ = timestampMS_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.contractId_ = contractId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.seqId_ = seqId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.contractSeqId_ = contractSeqId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.lastTrade_ = lastTradeBuilder_ == null
            ? lastTrade_
            : lastTradeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.orderbook.model.MarketDepth) {
        return mergeFrom((com.google.cloud.orderbook.model.MarketDepth)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.orderbook.model.MarketDepth other) {
      if (other == com.google.cloud.orderbook.model.MarketDepth.getDefaultInstance()) return this;
      if (other.getTimestampMS() != 0L) {
        setTimestampMS(other.getTimestampMS());
      }
      if (other.getContractId() != 0L) {
        setContractId(other.getContractId());
      }
      if (other.getMessageId() != 0L) {
        setMessageId(other.getMessageId());
      }
      if (other.getSeqId() != 0L) {
        setSeqId(other.getSeqId());
      }
      if (other.getContractSeqId() != 0L) {
        setContractSeqId(other.getContractSeqId());
      }
      if (bidsBuilder_ == null) {
        if (!other.bids_.isEmpty()) {
          if (bids_.isEmpty()) {
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureBidsIsMutable();
            bids_.addAll(other.bids_);
          }
          onChanged();
        }
      } else {
        if (!other.bids_.isEmpty()) {
          if (bidsBuilder_.isEmpty()) {
            bidsBuilder_.dispose();
            bidsBuilder_ = null;
            bids_ = other.bids_;
            bitField0_ = (bitField0_ & ~0x00000020);
            bidsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBidsFieldBuilder() : null;
          } else {
            bidsBuilder_.addAllMessages(other.bids_);
          }
        }
      }
      if (offersBuilder_ == null) {
        if (!other.offers_.isEmpty()) {
          if (offers_.isEmpty()) {
            offers_ = other.offers_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureOffersIsMutable();
            offers_.addAll(other.offers_);
          }
          onChanged();
        }
      } else {
        if (!other.offers_.isEmpty()) {
          if (offersBuilder_.isEmpty()) {
            offersBuilder_.dispose();
            offersBuilder_ = null;
            offers_ = other.offers_;
            bitField0_ = (bitField0_ & ~0x00000040);
            offersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOffersFieldBuilder() : null;
          } else {
            offersBuilder_.addAllMessages(other.offers_);
          }
        }
      }
      if (other.hasLastTrade()) {
        mergeLastTrade(other.getLastTrade());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestampMS_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              contractId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              messageId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              seqId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              contractSeqId_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              com.google.cloud.orderbook.model.MarketDepth.PriceQuantity m =
                  input.readMessage(
                      com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.parser(),
                      extensionRegistry);
              if (bidsBuilder_ == null) {
                ensureBidsIsMutable();
                bids_.add(m);
              } else {
                bidsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 58: {
              com.google.cloud.orderbook.model.MarketDepth.PriceQuantity m =
                  input.readMessage(
                      com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.parser(),
                      extensionRegistry);
              if (offersBuilder_ == null) {
                ensureOffersIsMutable();
                offers_.add(m);
              } else {
                offersBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getLastTradeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestampMS_ ;
    /**
     * <pre>
     * Millisecond timestmp
     * </pre>
     *
     * <code>int64 timestampMS = 1;</code>
     * @return The timestampMS.
     */
    @java.lang.Override
    public long getTimestampMS() {
      return timestampMS_;
    }
    /**
     * <pre>
     * Millisecond timestmp
     * </pre>
     *
     * <code>int64 timestampMS = 1;</code>
     * @param value The timestampMS to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMS(long value) {

      timestampMS_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Millisecond timestmp
     * </pre>
     *
     * <code>int64 timestampMS = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMS() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestampMS_ = 0L;
      onChanged();
      return this;
    }

    private long contractId_ ;
    /**
     * <pre>
     * Contract ID (unique ordering)
     * </pre>
     *
     * <code>int64 contractId = 2;</code>
     * @return The contractId.
     */
    @java.lang.Override
    public long getContractId() {
      return contractId_;
    }
    /**
     * <pre>
     * Contract ID (unique ordering)
     * </pre>
     *
     * <code>int64 contractId = 2;</code>
     * @param value The contractId to set.
     * @return This builder for chaining.
     */
    public Builder setContractId(long value) {

      contractId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contract ID (unique ordering)
     * </pre>
     *
     * <code>int64 contractId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      contractId_ = 0L;
      onChanged();
      return this;
    }

    private long messageId_ ;
    /**
     * <pre>
     * Message ID (corresponds to OrderBookEvent messageId)
     * </pre>
     *
     * <code>int64 messageId = 3;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * Message ID (corresponds to OrderBookEvent messageId)
     * </pre>
     *
     * <code>int64 messageId = 3;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(long value) {

      messageId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message ID (corresponds to OrderBookEvent messageId)
     * </pre>
     *
     * <code>int64 messageId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      messageId_ = 0L;
      onChanged();
      return this;
    }

    private long seqId_ ;
    /**
     * <pre>
     * Sequence IDs (global and per contract) will skip
     * any updates that do not generate a market depth.
     * </pre>
     *
     * <code>int64 seqId = 4;</code>
     * @return The seqId.
     */
    @java.lang.Override
    public long getSeqId() {
      return seqId_;
    }
    /**
     * <pre>
     * Sequence IDs (global and per contract) will skip
     * any updates that do not generate a market depth.
     * </pre>
     *
     * <code>int64 seqId = 4;</code>
     * @param value The seqId to set.
     * @return This builder for chaining.
     */
    public Builder setSeqId(long value) {

      seqId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sequence IDs (global and per contract) will skip
     * any updates that do not generate a market depth.
     * </pre>
     *
     * <code>int64 seqId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      seqId_ = 0L;
      onChanged();
      return this;
    }

    private long contractSeqId_ ;
    /**
     * <code>int64 contractSeqId = 5;</code>
     * @return The contractSeqId.
     */
    @java.lang.Override
    public long getContractSeqId() {
      return contractSeqId_;
    }
    /**
     * <code>int64 contractSeqId = 5;</code>
     * @param value The contractSeqId to set.
     * @return This builder for chaining.
     */
    public Builder setContractSeqId(long value) {

      contractSeqId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 contractSeqId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractSeqId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      contractSeqId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> bids_ =
      java.util.Collections.emptyList();
    private void ensureBidsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        bids_ = new java.util.ArrayList<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity>(bids_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> bidsBuilder_;

    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> getBidsList() {
      if (bidsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bids_);
      } else {
        return bidsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public int getBidsCount() {
      if (bidsBuilder_ == null) {
        return bids_.size();
      } else {
        return bidsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getBids(int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);
      } else {
        return bidsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder setBids(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.set(index, value);
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder setBids(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.set(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder addBids(com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder addBids(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (bidsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBidsIsMutable();
        bids_.add(index, value);
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder addBids(
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder addBids(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder builderForValue) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.add(index, builderForValue.build());
        onChanged();
      } else {
        bidsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder addAllBids(
        java.lang.Iterable<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> values) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bids_);
        onChanged();
      } else {
        bidsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder clearBids() {
      if (bidsBuilder_ == null) {
        bids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        bidsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public Builder removeBids(int index) {
      if (bidsBuilder_ == null) {
        ensureBidsIsMutable();
        bids_.remove(index);
        onChanged();
      } else {
        bidsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder getBidsBuilder(
        int index) {
      return getBidsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getBidsOrBuilder(
        int index) {
      if (bidsBuilder_ == null) {
        return bids_.get(index);  } else {
        return bidsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public java.util.List<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
         getBidsOrBuilderList() {
      if (bidsBuilder_ != null) {
        return bidsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bids_);
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder addBidsBuilder() {
      return getBidsFieldBuilder().addBuilder(
          com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance());
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder addBidsBuilder(
        int index) {
      return getBidsFieldBuilder().addBuilder(
          index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance());
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
     */
    public java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder> 
         getBidsBuilderList() {
      return getBidsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
        getBidsFieldBuilder() {
      if (bidsBuilder_ == null) {
        bidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder>(
                bids_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        bids_ = null;
      }
      return bidsBuilder_;
    }

    private java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> offers_ =
      java.util.Collections.emptyList();
    private void ensureOffersIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        offers_ = new java.util.ArrayList<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity>(offers_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> offersBuilder_;

    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> getOffersList() {
      if (offersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(offers_);
      } else {
        return offersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public int getOffersCount() {
      if (offersBuilder_ == null) {
        return offers_.size();
      } else {
        return offersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getOffers(int index) {
      if (offersBuilder_ == null) {
        return offers_.get(index);
      } else {
        return offersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder setOffers(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (offersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffersIsMutable();
        offers_.set(index, value);
        onChanged();
      } else {
        offersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder setOffers(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder builderForValue) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.set(index, builderForValue.build());
        onChanged();
      } else {
        offersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder addOffers(com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (offersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffersIsMutable();
        offers_.add(value);
        onChanged();
      } else {
        offersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder addOffers(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (offersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffersIsMutable();
        offers_.add(index, value);
        onChanged();
      } else {
        offersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder addOffers(
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder builderForValue) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.add(builderForValue.build());
        onChanged();
      } else {
        offersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder addOffers(
        int index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder builderForValue) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.add(index, builderForValue.build());
        onChanged();
      } else {
        offersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder addAllOffers(
        java.lang.Iterable<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> values) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, offers_);
        onChanged();
      } else {
        offersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder clearOffers() {
      if (offersBuilder_ == null) {
        offers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        offersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public Builder removeOffers(int index) {
      if (offersBuilder_ == null) {
        ensureOffersIsMutable();
        offers_.remove(index);
        onChanged();
      } else {
        offersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder getOffersBuilder(
        int index) {
      return getOffersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getOffersOrBuilder(
        int index) {
      if (offersBuilder_ == null) {
        return offers_.get(index);  } else {
        return offersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public java.util.List<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
         getOffersOrBuilderList() {
      if (offersBuilder_ != null) {
        return offersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(offers_);
      }
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder addOffersBuilder() {
      return getOffersFieldBuilder().addBuilder(
          com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance());
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder addOffersBuilder(
        int index) {
      return getOffersFieldBuilder().addBuilder(
          index, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance());
    }
    /**
     * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
     */
    public java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder> 
         getOffersBuilderList() {
      return getOffersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
        getOffersFieldBuilder() {
      if (offersBuilder_ == null) {
        offersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder>(
                offers_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        offers_ = null;
      }
      return offersBuilder_;
    }

    private com.google.cloud.orderbook.model.MarketDepth.PriceQuantity lastTrade_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> lastTradeBuilder_;
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     * @return Whether the lastTrade field is set.
     */
    public boolean hasLastTrade() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     * @return The lastTrade.
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getLastTrade() {
      if (lastTradeBuilder_ == null) {
        return lastTrade_ == null ? com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance() : lastTrade_;
      } else {
        return lastTradeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     */
    public Builder setLastTrade(com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (lastTradeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastTrade_ = value;
      } else {
        lastTradeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     */
    public Builder setLastTrade(
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder builderForValue) {
      if (lastTradeBuilder_ == null) {
        lastTrade_ = builderForValue.build();
      } else {
        lastTradeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     */
    public Builder mergeLastTrade(com.google.cloud.orderbook.model.MarketDepth.PriceQuantity value) {
      if (lastTradeBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          lastTrade_ != null &&
          lastTrade_ != com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance()) {
          getLastTradeBuilder().mergeFrom(value);
        } else {
          lastTrade_ = value;
        }
      } else {
        lastTradeBuilder_.mergeFrom(value);
      }
      if (lastTrade_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     */
    public Builder clearLastTrade() {
      bitField0_ = (bitField0_ & ~0x00000080);
      lastTrade_ = null;
      if (lastTradeBuilder_ != null) {
        lastTradeBuilder_.dispose();
        lastTradeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder getLastTradeBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getLastTradeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     */
    public com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getLastTradeOrBuilder() {
      if (lastTradeBuilder_ != null) {
        return lastTradeBuilder_.getMessageOrBuilder();
      } else {
        return lastTrade_ == null ?
            com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.getDefaultInstance() : lastTrade_;
      }
    }
    /**
     * <pre>
     * If a trade was executed for this event,
     * capture this here.
     * </pre>
     *
     * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
        getLastTradeFieldBuilder() {
      if (lastTradeBuilder_ == null) {
        lastTradeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.orderbook.model.MarketDepth.PriceQuantity, com.google.cloud.orderbook.model.MarketDepth.PriceQuantity.Builder, com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder>(
                getLastTrade(),
                getParentForChildren(),
                isClean());
        lastTrade_ = null;
      }
      return lastTradeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MarketDepth)
  }

  // @@protoc_insertion_point(class_scope:MarketDepth)
  private static final com.google.cloud.orderbook.model.MarketDepth DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.orderbook.model.MarketDepth();
  }

  public static com.google.cloud.orderbook.model.MarketDepth getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MarketDepth>
      PARSER = new com.google.protobuf.AbstractParser<MarketDepth>() {
    @java.lang.Override
    public MarketDepth parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MarketDepth> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MarketDepth> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.orderbook.model.MarketDepth getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

