/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata.proto

// Protobuf Java Version: 3.25.0
package com.google.cloud.orderbook.model;

public final class MarketData {
  private MarketData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderBookEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderBookEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MarketDepth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MarketDepth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MarketDepth_PriceQuantity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MarketDepth_PriceQuantity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020marketdata.proto\"\332\003\n\016OrderBookEvent\022\023\n" +
      "\013timestampMS\030\001 \001(\003\022\022\n\ncontractId\030\002 \001(\003\022\021" +
      "\n\tmessageId\030\003 \001(\003\022\r\n\005seqId\030\004 \001(\003\022\025\n\rcont" +
      "ractSeqId\030\005 \001(\003\022\023\n\013lastMessage\030\006 \001(\010\022\033\n\023" +
      "lastContractMessage\030\007 \001(\010\022\"\n\004type\030\010 \001(\0162" +
      "\024.OrderBookEvent.Type\022\017\n\007orderId\030\t \001(\003\022\"" +
      "\n\004side\030\n \001(\0162\024.OrderBookEvent.Side\022\r\n\005pr" +
      "ice\030\013 \001(\003\022\020\n\010quantity\030\014 \001(\003\022\031\n\021quantityR" +
      "emaining\030\r \001(\003\022\026\n\016quantityFilled\030\016 \001(\003\022\023" +
      "\n\013matchNumber\030\017 \001(\003\"A\n\004Type\022\025\n\021UNSPECIFI" +
      "ED_ORDER\020\000\022\007\n\003NEW\020\001\022\014\n\010EXECUTED\020\002\022\013\n\007DEL" +
      "ETED\020\003\"/\n\004Side\022\024\n\020UNSPECIFIED_SIDE\020\000\022\007\n\003" +
      "BUY\020\001\022\010\n\004SELL\020\002\"\246\002\n\013MarketDepth\022\023\n\013times" +
      "tampMS\030\001 \001(\003\022\022\n\ncontractId\030\002 \001(\003\022\021\n\tmess" +
      "ageId\030\003 \001(\003\022\r\n\005seqId\030\004 \001(\003\022\025\n\rcontractSe" +
      "qId\030\005 \001(\003\022(\n\004bids\030\006 \003(\0132\032.MarketDepth.Pr" +
      "iceQuantity\022*\n\006offers\030\007 \003(\0132\032.MarketDept" +
      "h.PriceQuantity\022-\n\tlastTrade\030\010 \001(\0132\032.Mar" +
      "ketDepth.PriceQuantity\0320\n\rPriceQuantity\022" +
      "\r\n\005price\030\001 \001(\003\022\020\n\010quantity\030\002 \001(\003B0\n com." +
      "google.cloud.orderbook.modelB\nMarketData" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OrderBookEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderBookEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderBookEvent_descriptor,
        new java.lang.String[] { "TimestampMS", "ContractId", "MessageId", "SeqId", "ContractSeqId", "LastMessage", "LastContractMessage", "Type", "OrderId", "Side", "Price", "Quantity", "QuantityRemaining", "QuantityFilled", "MatchNumber", });
    internal_static_MarketDepth_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MarketDepth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MarketDepth_descriptor,
        new java.lang.String[] { "TimestampMS", "ContractId", "MessageId", "SeqId", "ContractSeqId", "Bids", "Offers", "LastTrade", });
    internal_static_MarketDepth_PriceQuantity_descriptor =
      internal_static_MarketDepth_descriptor.getNestedTypes().get(0);
    internal_static_MarketDepth_PriceQuantity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MarketDepth_PriceQuantity_descriptor,
        new java.lang.String[] { "Price", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
