/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata.proto

// Protobuf Java Version: 3.25.0
package com.google.cloud.orderbook.model;

public interface MarketDepthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MarketDepth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Millisecond timestmp
   * </pre>
   *
   * <code>int64 timestampMS = 1;</code>
   * @return The timestampMS.
   */
  long getTimestampMS();

  /**
   * <pre>
   * Contract ID (unique ordering)
   * </pre>
   *
   * <code>int64 contractId = 2;</code>
   * @return The contractId.
   */
  long getContractId();

  /**
   * <pre>
   * Sequence IDs (global and per contract) will skip
   * any updates that do not generate a market depth.
   * </pre>
   *
   * <code>int64 seqId = 4;</code>
   * @return The seqId.
   */
  long getSeqId();

  /**
   * <code>int64 contractSeqId = 5;</code>
   * @return The contractSeqId.
   */
  long getContractSeqId();

  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> 
      getBidsList();
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getBids(int index);
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  int getBidsCount();
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  java.util.List<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
      getBidsOrBuilderList();
  /**
   * <code>repeated .MarketDepth.PriceQuantity bids = 6;</code>
   */
  com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getBidsOrBuilder(
      int index);

  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  java.util.List<com.google.cloud.orderbook.model.MarketDepth.PriceQuantity> 
      getOffersList();
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getOffers(int index);
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  int getOffersCount();
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  java.util.List<? extends com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder> 
      getOffersOrBuilderList();
  /**
   * <code>repeated .MarketDepth.PriceQuantity offers = 7;</code>
   */
  com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getOffersOrBuilder(
      int index);

  /**
   * <pre>
   * If a trade was executed for this event,
   * capture this here.
   * </pre>
   *
   * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
   * @return Whether the lastTrade field is set.
   */
  boolean hasLastTrade();
  /**
   * <pre>
   * If a trade was executed for this event,
   * capture this here.
   * </pre>
   *
   * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
   * @return The lastTrade.
   */
  com.google.cloud.orderbook.model.MarketDepth.PriceQuantity getLastTrade();
  /**
   * <pre>
   * If a trade was executed for this event,
   * capture this here.
   * </pre>
   *
   * <code>.MarketDepth.PriceQuantity lastTrade = 8;</code>
   */
  com.google.cloud.orderbook.model.MarketDepth.PriceQuantityOrBuilder getLastTradeOrBuilder();
}
