// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marketdata.proto

package com.google.cloud.orderbook.model;

/**
 * Protobuf type {@code OrderBookEvent}
 */
public final class OrderBookEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OrderBookEvent)
    OrderBookEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderBookEvent.newBuilder() to construct.
  private OrderBookEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderBookEvent() {
    type_ = 0;
    side_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderBookEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.orderbook.model.MarketData.internal_static_OrderBookEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.orderbook.model.MarketData.internal_static_OrderBookEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.orderbook.model.OrderBookEvent.class, com.google.cloud.orderbook.model.OrderBookEvent.Builder.class);
  }

  /**
   * <pre>
   * Event type
   * NOTE: Aggressive matching orders will
   * never issue a NEW or DELETED event, unless
   * there is a quantity that becomes passive.
   * </pre>
   *
   * Protobuf enum {@code OrderBookEvent.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSPECIFIED_ORDER = 0;</code>
     */
    UNSPECIFIED_ORDER(0),
    /**
     * <code>NEW = 1;</code>
     */
    NEW(1),
    /**
     * <code>EXECUTED = 2;</code>
     */
    EXECUTED(2),
    /**
     * <code>DELETED = 3;</code>
     */
    DELETED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSPECIFIED_ORDER = 0;</code>
     */
    public static final int UNSPECIFIED_ORDER_VALUE = 0;
    /**
     * <code>NEW = 1;</code>
     */
    public static final int NEW_VALUE = 1;
    /**
     * <code>EXECUTED = 2;</code>
     */
    public static final int EXECUTED_VALUE = 2;
    /**
     * <code>DELETED = 3;</code>
     */
    public static final int DELETED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED_ORDER;
        case 1: return NEW;
        case 2: return EXECUTED;
        case 3: return DELETED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.cloud.orderbook.model.OrderBookEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OrderBookEvent.Type)
  }

  /**
   * <pre>
   * Side for the passive order.
   * </pre>
   *
   * Protobuf enum {@code OrderBookEvent.Side}
   */
  public enum Side
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSPECIFIED_SIDE = 0;</code>
     */
    UNSPECIFIED_SIDE(0),
    /**
     * <code>BUY = 1;</code>
     */
    BUY(1),
    /**
     * <code>SELL = 2;</code>
     */
    SELL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSPECIFIED_SIDE = 0;</code>
     */
    public static final int UNSPECIFIED_SIDE_VALUE = 0;
    /**
     * <code>BUY = 1;</code>
     */
    public static final int BUY_VALUE = 1;
    /**
     * <code>SELL = 2;</code>
     */
    public static final int SELL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Side valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Side forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED_SIDE;
        case 1: return BUY;
        case 2: return SELL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Side>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Side> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Side>() {
            public Side findValueByNumber(int number) {
              return Side.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.cloud.orderbook.model.OrderBookEvent.getDescriptor().getEnumTypes().get(1);
    }

    private static final Side[] VALUES = values();

    public static Side valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Side(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OrderBookEvent.Side)
  }

  public static final int TIMESTAMPMS_FIELD_NUMBER = 1;
  private long timestampMS_ = 0L;
  /**
   * <pre>
   * Millisecond timestamp
   * </pre>
   *
   * <code>int64 timestampMS = 1;</code>
   * @return The timestampMS.
   */
  @java.lang.Override
  public long getTimestampMS() {
    return timestampMS_;
  }

  public static final int CONTRACTID_FIELD_NUMBER = 2;
  private long contractId_ = 0L;
  /**
   * <pre>
   * Contract ID (unique ordering)
   * </pre>
   *
   * <code>int64 contractId = 2;</code>
   * @return The contractId.
   */
  @java.lang.Override
  public long getContractId() {
    return contractId_;
  }

  public static final int MESSAGEID_FIELD_NUMBER = 3;
  private long messageId_ = 0L;
  /**
   * <pre>
   * Message ID
   * </pre>
   *
   * <code>int64 messageId = 3;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public long getMessageId() {
    return messageId_;
  }

  public static final int SEQID_FIELD_NUMBER = 4;
  private long seqId_ = 0L;
  /**
   * <pre>
   * Global and per-contract sequence ID.
   * </pre>
   *
   * <code>int64 seqId = 4;</code>
   * @return The seqId.
   */
  @java.lang.Override
  public long getSeqId() {
    return seqId_;
  }

  public static final int CONTRACTSEQID_FIELD_NUMBER = 5;
  private long contractSeqId_ = 0L;
  /**
   * <code>int64 contractSeqId = 5;</code>
   * @return The contractSeqId.
   */
  @java.lang.Override
  public long getContractSeqId() {
    return contractSeqId_;
  }

  public static final int TYPE_FIELD_NUMBER = 6;
  private int type_ = 0;
  /**
   * <code>.OrderBookEvent.Type type = 6;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.OrderBookEvent.Type type = 6;</code>
   * @return The type.
   */
  @java.lang.Override public com.google.cloud.orderbook.model.OrderBookEvent.Type getType() {
    com.google.cloud.orderbook.model.OrderBookEvent.Type result = com.google.cloud.orderbook.model.OrderBookEvent.Type.forNumber(type_);
    return result == null ? com.google.cloud.orderbook.model.OrderBookEvent.Type.UNRECOGNIZED : result;
  }

  public static final int ORDERID_FIELD_NUMBER = 7;
  private long orderId_ = 0L;
  /**
   * <pre>
   * OrderID for the passive order.
   * </pre>
   *
   * <code>int64 orderId = 7;</code>
   * @return The orderId.
   */
  @java.lang.Override
  public long getOrderId() {
    return orderId_;
  }

  public static final int SIDE_FIELD_NUMBER = 8;
  private int side_ = 0;
  /**
   * <pre>
   * enum Buy/Sell
   * </pre>
   *
   * <code>.OrderBookEvent.Side side = 8;</code>
   * @return The enum numeric value on the wire for side.
   */
  @java.lang.Override public int getSideValue() {
    return side_;
  }
  /**
   * <pre>
   * enum Buy/Sell
   * </pre>
   *
   * <code>.OrderBookEvent.Side side = 8;</code>
   * @return The side.
   */
  @java.lang.Override public com.google.cloud.orderbook.model.OrderBookEvent.Side getSide() {
    com.google.cloud.orderbook.model.OrderBookEvent.Side result = com.google.cloud.orderbook.model.OrderBookEvent.Side.forNumber(side_);
    return result == null ? com.google.cloud.orderbook.model.OrderBookEvent.Side.UNRECOGNIZED : result;
  }

  public static final int PRICE_FIELD_NUMBER = 9;
  private long price_ = 0L;
  /**
   * <code>int64 price = 9;</code>
   * @return The price.
   */
  @java.lang.Override
  public long getPrice() {
    return price_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 10;
  private long quantity_ = 0L;
  /**
   * <code>int64 quantity = 10;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public long getQuantity() {
    return quantity_;
  }

  public static final int QUANTITYREMAINING_FIELD_NUMBER = 11;
  private long quantityRemaining_ = 0L;
  /**
   * <code>int64 quantityRemaining = 11;</code>
   * @return The quantityRemaining.
   */
  @java.lang.Override
  public long getQuantityRemaining() {
    return quantityRemaining_;
  }

  public static final int QUANTITYFILLED_FIELD_NUMBER = 12;
  private long quantityFilled_ = 0L;
  /**
   * <code>int64 quantityFilled = 12;</code>
   * @return The quantityFilled.
   */
  @java.lang.Override
  public long getQuantityFilled() {
    return quantityFilled_;
  }

  public static final int MATCHNUMBER_FIELD_NUMBER = 13;
  private long matchNumber_ = 0L;
  /**
   * <pre>
   * If it is an execution, record the matchNumber
   * </pre>
   *
   * <code>int64 matchNumber = 13;</code>
   * @return The matchNumber.
   */
  @java.lang.Override
  public long getMatchNumber() {
    return matchNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestampMS_ != 0L) {
      output.writeInt64(1, timestampMS_);
    }
    if (contractId_ != 0L) {
      output.writeInt64(2, contractId_);
    }
    if (messageId_ != 0L) {
      output.writeInt64(3, messageId_);
    }
    if (seqId_ != 0L) {
      output.writeInt64(4, seqId_);
    }
    if (contractSeqId_ != 0L) {
      output.writeInt64(5, contractSeqId_);
    }
    if (type_ != com.google.cloud.orderbook.model.OrderBookEvent.Type.UNSPECIFIED_ORDER.getNumber()) {
      output.writeEnum(6, type_);
    }
    if (orderId_ != 0L) {
      output.writeInt64(7, orderId_);
    }
    if (side_ != com.google.cloud.orderbook.model.OrderBookEvent.Side.UNSPECIFIED_SIDE.getNumber()) {
      output.writeEnum(8, side_);
    }
    if (price_ != 0L) {
      output.writeInt64(9, price_);
    }
    if (quantity_ != 0L) {
      output.writeInt64(10, quantity_);
    }
    if (quantityRemaining_ != 0L) {
      output.writeInt64(11, quantityRemaining_);
    }
    if (quantityFilled_ != 0L) {
      output.writeInt64(12, quantityFilled_);
    }
    if (matchNumber_ != 0L) {
      output.writeInt64(13, matchNumber_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestampMS_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestampMS_);
    }
    if (contractId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, contractId_);
    }
    if (messageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, messageId_);
    }
    if (seqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, seqId_);
    }
    if (contractSeqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, contractSeqId_);
    }
    if (type_ != com.google.cloud.orderbook.model.OrderBookEvent.Type.UNSPECIFIED_ORDER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, type_);
    }
    if (orderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, orderId_);
    }
    if (side_ != com.google.cloud.orderbook.model.OrderBookEvent.Side.UNSPECIFIED_SIDE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, side_);
    }
    if (price_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, price_);
    }
    if (quantity_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, quantity_);
    }
    if (quantityRemaining_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, quantityRemaining_);
    }
    if (quantityFilled_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, quantityFilled_);
    }
    if (matchNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, matchNumber_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.orderbook.model.OrderBookEvent)) {
      return super.equals(obj);
    }
    com.google.cloud.orderbook.model.OrderBookEvent other = (com.google.cloud.orderbook.model.OrderBookEvent) obj;

    if (getTimestampMS()
        != other.getTimestampMS()) return false;
    if (getContractId()
        != other.getContractId()) return false;
    if (getMessageId()
        != other.getMessageId()) return false;
    if (getSeqId()
        != other.getSeqId()) return false;
    if (getContractSeqId()
        != other.getContractSeqId()) return false;
    if (type_ != other.type_) return false;
    if (getOrderId()
        != other.getOrderId()) return false;
    if (side_ != other.side_) return false;
    if (getPrice()
        != other.getPrice()) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (getQuantityRemaining()
        != other.getQuantityRemaining()) return false;
    if (getQuantityFilled()
        != other.getQuantityFilled()) return false;
    if (getMatchNumber()
        != other.getMatchNumber()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMPMS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMS());
    hash = (37 * hash) + CONTRACTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getContractId());
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageId());
    hash = (37 * hash) + SEQID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeqId());
    hash = (37 * hash) + CONTRACTSEQID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getContractSeqId());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOrderId());
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrice());
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuantity());
    hash = (37 * hash) + QUANTITYREMAINING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuantityRemaining());
    hash = (37 * hash) + QUANTITYFILLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuantityFilled());
    hash = (37 * hash) + MATCHNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMatchNumber());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.orderbook.model.OrderBookEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.orderbook.model.OrderBookEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.orderbook.model.OrderBookEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.orderbook.model.OrderBookEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OrderBookEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OrderBookEvent)
      com.google.cloud.orderbook.model.OrderBookEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_OrderBookEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_OrderBookEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.orderbook.model.OrderBookEvent.class, com.google.cloud.orderbook.model.OrderBookEvent.Builder.class);
    }

    // Construct using com.google.cloud.orderbook.model.OrderBookEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestampMS_ = 0L;
      contractId_ = 0L;
      messageId_ = 0L;
      seqId_ = 0L;
      contractSeqId_ = 0L;
      type_ = 0;
      orderId_ = 0L;
      side_ = 0;
      price_ = 0L;
      quantity_ = 0L;
      quantityRemaining_ = 0L;
      quantityFilled_ = 0L;
      matchNumber_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.orderbook.model.MarketData.internal_static_OrderBookEvent_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.orderbook.model.OrderBookEvent getDefaultInstanceForType() {
      return com.google.cloud.orderbook.model.OrderBookEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.orderbook.model.OrderBookEvent build() {
      com.google.cloud.orderbook.model.OrderBookEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.orderbook.model.OrderBookEvent buildPartial() {
      com.google.cloud.orderbook.model.OrderBookEvent result = new com.google.cloud.orderbook.model.OrderBookEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.cloud.orderbook.model.OrderBookEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestampMS_ = timestampMS_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.contractId_ = contractId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.seqId_ = seqId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.contractSeqId_ = contractSeqId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.orderId_ = orderId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.side_ = side_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.quantityRemaining_ = quantityRemaining_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.quantityFilled_ = quantityFilled_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.matchNumber_ = matchNumber_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.orderbook.model.OrderBookEvent) {
        return mergeFrom((com.google.cloud.orderbook.model.OrderBookEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.orderbook.model.OrderBookEvent other) {
      if (other == com.google.cloud.orderbook.model.OrderBookEvent.getDefaultInstance()) return this;
      if (other.getTimestampMS() != 0L) {
        setTimestampMS(other.getTimestampMS());
      }
      if (other.getContractId() != 0L) {
        setContractId(other.getContractId());
      }
      if (other.getMessageId() != 0L) {
        setMessageId(other.getMessageId());
      }
      if (other.getSeqId() != 0L) {
        setSeqId(other.getSeqId());
      }
      if (other.getContractSeqId() != 0L) {
        setContractSeqId(other.getContractSeqId());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getOrderId() != 0L) {
        setOrderId(other.getOrderId());
      }
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.getPrice() != 0L) {
        setPrice(other.getPrice());
      }
      if (other.getQuantity() != 0L) {
        setQuantity(other.getQuantity());
      }
      if (other.getQuantityRemaining() != 0L) {
        setQuantityRemaining(other.getQuantityRemaining());
      }
      if (other.getQuantityFilled() != 0L) {
        setQuantityFilled(other.getQuantityFilled());
      }
      if (other.getMatchNumber() != 0L) {
        setMatchNumber(other.getMatchNumber());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestampMS_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              contractId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              messageId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              seqId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              contractSeqId_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              orderId_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              side_ = input.readEnum();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              price_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              quantity_ = input.readInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              quantityRemaining_ = input.readInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              quantityFilled_ = input.readInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              matchNumber_ = input.readInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestampMS_ ;
    /**
     * <pre>
     * Millisecond timestamp
     * </pre>
     *
     * <code>int64 timestampMS = 1;</code>
     * @return The timestampMS.
     */
    @java.lang.Override
    public long getTimestampMS() {
      return timestampMS_;
    }
    /**
     * <pre>
     * Millisecond timestamp
     * </pre>
     *
     * <code>int64 timestampMS = 1;</code>
     * @param value The timestampMS to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMS(long value) {

      timestampMS_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Millisecond timestamp
     * </pre>
     *
     * <code>int64 timestampMS = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMS() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestampMS_ = 0L;
      onChanged();
      return this;
    }

    private long contractId_ ;
    /**
     * <pre>
     * Contract ID (unique ordering)
     * </pre>
     *
     * <code>int64 contractId = 2;</code>
     * @return The contractId.
     */
    @java.lang.Override
    public long getContractId() {
      return contractId_;
    }
    /**
     * <pre>
     * Contract ID (unique ordering)
     * </pre>
     *
     * <code>int64 contractId = 2;</code>
     * @param value The contractId to set.
     * @return This builder for chaining.
     */
    public Builder setContractId(long value) {

      contractId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Contract ID (unique ordering)
     * </pre>
     *
     * <code>int64 contractId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      contractId_ = 0L;
      onChanged();
      return this;
    }

    private long messageId_ ;
    /**
     * <pre>
     * Message ID
     * </pre>
     *
     * <code>int64 messageId = 3;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     * Message ID
     * </pre>
     *
     * <code>int64 messageId = 3;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(long value) {

      messageId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message ID
     * </pre>
     *
     * <code>int64 messageId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      messageId_ = 0L;
      onChanged();
      return this;
    }

    private long seqId_ ;
    /**
     * <pre>
     * Global and per-contract sequence ID.
     * </pre>
     *
     * <code>int64 seqId = 4;</code>
     * @return The seqId.
     */
    @java.lang.Override
    public long getSeqId() {
      return seqId_;
    }
    /**
     * <pre>
     * Global and per-contract sequence ID.
     * </pre>
     *
     * <code>int64 seqId = 4;</code>
     * @param value The seqId to set.
     * @return This builder for chaining.
     */
    public Builder setSeqId(long value) {

      seqId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Global and per-contract sequence ID.
     * </pre>
     *
     * <code>int64 seqId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      seqId_ = 0L;
      onChanged();
      return this;
    }

    private long contractSeqId_ ;
    /**
     * <code>int64 contractSeqId = 5;</code>
     * @return The contractSeqId.
     */
    @java.lang.Override
    public long getContractSeqId() {
      return contractSeqId_;
    }
    /**
     * <code>int64 contractSeqId = 5;</code>
     * @param value The contractSeqId to set.
     * @return This builder for chaining.
     */
    public Builder setContractSeqId(long value) {

      contractSeqId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 contractSeqId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractSeqId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      contractSeqId_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.OrderBookEvent.Type type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.OrderBookEvent.Type type = 6;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.OrderBookEvent.Type type = 6;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.google.cloud.orderbook.model.OrderBookEvent.Type getType() {
      com.google.cloud.orderbook.model.OrderBookEvent.Type result = com.google.cloud.orderbook.model.OrderBookEvent.Type.forNumber(type_);
      return result == null ? com.google.cloud.orderbook.model.OrderBookEvent.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.OrderBookEvent.Type type = 6;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.google.cloud.orderbook.model.OrderBookEvent.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.OrderBookEvent.Type type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      type_ = 0;
      onChanged();
      return this;
    }

    private long orderId_ ;
    /**
     * <pre>
     * OrderID for the passive order.
     * </pre>
     *
     * <code>int64 orderId = 7;</code>
     * @return The orderId.
     */
    @java.lang.Override
    public long getOrderId() {
      return orderId_;
    }
    /**
     * <pre>
     * OrderID for the passive order.
     * </pre>
     *
     * <code>int64 orderId = 7;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(long value) {

      orderId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OrderID for the passive order.
     * </pre>
     *
     * <code>int64 orderId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      bitField0_ = (bitField0_ & ~0x00000040);
      orderId_ = 0L;
      onChanged();
      return this;
    }

    private int side_ = 0;
    /**
     * <pre>
     * enum Buy/Sell
     * </pre>
     *
     * <code>.OrderBookEvent.Side side = 8;</code>
     * @return The enum numeric value on the wire for side.
     */
    @java.lang.Override public int getSideValue() {
      return side_;
    }
    /**
     * <pre>
     * enum Buy/Sell
     * </pre>
     *
     * <code>.OrderBookEvent.Side side = 8;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * enum Buy/Sell
     * </pre>
     *
     * <code>.OrderBookEvent.Side side = 8;</code>
     * @return The side.
     */
    @java.lang.Override
    public com.google.cloud.orderbook.model.OrderBookEvent.Side getSide() {
      com.google.cloud.orderbook.model.OrderBookEvent.Side result = com.google.cloud.orderbook.model.OrderBookEvent.Side.forNumber(side_);
      return result == null ? com.google.cloud.orderbook.model.OrderBookEvent.Side.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * enum Buy/Sell
     * </pre>
     *
     * <code>.OrderBookEvent.Side side = 8;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(com.google.cloud.orderbook.model.OrderBookEvent.Side value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * enum Buy/Sell
     * </pre>
     *
     * <code>.OrderBookEvent.Side side = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      bitField0_ = (bitField0_ & ~0x00000080);
      side_ = 0;
      onChanged();
      return this;
    }

    private long price_ ;
    /**
     * <code>int64 price = 9;</code>
     * @return The price.
     */
    @java.lang.Override
    public long getPrice() {
      return price_;
    }
    /**
     * <code>int64 price = 9;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(long value) {

      price_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 price = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000100);
      price_ = 0L;
      onChanged();
      return this;
    }

    private long quantity_ ;
    /**
     * <code>int64 quantity = 10;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public long getQuantity() {
      return quantity_;
    }
    /**
     * <code>int64 quantity = 10;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(long value) {

      quantity_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int64 quantity = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000200);
      quantity_ = 0L;
      onChanged();
      return this;
    }

    private long quantityRemaining_ ;
    /**
     * <code>int64 quantityRemaining = 11;</code>
     * @return The quantityRemaining.
     */
    @java.lang.Override
    public long getQuantityRemaining() {
      return quantityRemaining_;
    }
    /**
     * <code>int64 quantityRemaining = 11;</code>
     * @param value The quantityRemaining to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityRemaining(long value) {

      quantityRemaining_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int64 quantityRemaining = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantityRemaining() {
      bitField0_ = (bitField0_ & ~0x00000400);
      quantityRemaining_ = 0L;
      onChanged();
      return this;
    }

    private long quantityFilled_ ;
    /**
     * <code>int64 quantityFilled = 12;</code>
     * @return The quantityFilled.
     */
    @java.lang.Override
    public long getQuantityFilled() {
      return quantityFilled_;
    }
    /**
     * <code>int64 quantityFilled = 12;</code>
     * @param value The quantityFilled to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityFilled(long value) {

      quantityFilled_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int64 quantityFilled = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantityFilled() {
      bitField0_ = (bitField0_ & ~0x00000800);
      quantityFilled_ = 0L;
      onChanged();
      return this;
    }

    private long matchNumber_ ;
    /**
     * <pre>
     * If it is an execution, record the matchNumber
     * </pre>
     *
     * <code>int64 matchNumber = 13;</code>
     * @return The matchNumber.
     */
    @java.lang.Override
    public long getMatchNumber() {
      return matchNumber_;
    }
    /**
     * <pre>
     * If it is an execution, record the matchNumber
     * </pre>
     *
     * <code>int64 matchNumber = 13;</code>
     * @param value The matchNumber to set.
     * @return This builder for chaining.
     */
    public Builder setMatchNumber(long value) {

      matchNumber_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If it is an execution, record the matchNumber
     * </pre>
     *
     * <code>int64 matchNumber = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatchNumber() {
      bitField0_ = (bitField0_ & ~0x00001000);
      matchNumber_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OrderBookEvent)
  }

  // @@protoc_insertion_point(class_scope:OrderBookEvent)
  private static final com.google.cloud.orderbook.model.OrderBookEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.orderbook.model.OrderBookEvent();
  }

  public static com.google.cloud.orderbook.model.OrderBookEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderBookEvent>
      PARSER = new com.google.protobuf.AbstractParser<OrderBookEvent>() {
    @java.lang.Override
    public OrderBookEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OrderBookEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderBookEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.orderbook.model.OrderBookEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

